FROM public.ecr.aws/docker/library/amazonlinux:latest

# Set environment
ENV NODE_VERSION=20.12.2
ENV NVM_VERSION=0.39.1
ENV NVM_DIR=/root/.nvm
ENV BASH_ENV="~/.bashrc"
SHELL ["/bin/bash", "-c"]

# Update system and install necessary utilities
RUN yum -y update && \
    yum install -y yum-utils shadow-utils tar unzip && \
    yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo && \
    yum -y install terraform

# Install NVM
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash && \
    echo 'export NVM_DIR="/root/.nvm"' >> ~/.bashrc && \
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.bashrc

# Install Node.js
RUN . "$NVM_DIR/nvm.sh" && nvm install $NODE_VERSION && nvm use $NODE_VERSION && \
    npm install -g @aws-amplify/cli --verbose

ENTRYPOINT [ "bash" ]
