FROM public.ecr.aws/codebuild/amazonlinux-x86_64-lambda-standard:python3.11

ENV TERRAFORM_VERSION=1.7.5
ENV TF_DEV=true
ENV TF_RELEASE=true

RUN yum install -y yum-utils shadow-utils
RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
RUN yum -y install terraform












